---
- name: ensure apt cache is up to date
  apt: update_cache=yes
- name: ensure python-software-properties is installed
  apt: pkg=python-software-properties
- name: ensure app apt dependencies are installed
  apt: pkg=$item
  with_items:
    - openjdk-7-jre

- name: ensure we have the elasticsearch .deb
  get_url: url=https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-${es_version}.deb dest=/tmp/elasticsearch-${es_version}.deb mode=0644

- name: ensure elasticsearch is installed
  shell: dpkg -i /tmp/elasticsearch-${es_version}.deb creates=/etc/elasticsearch
  notify: restart elasticsearch
- name: Make elasticsearch listen on a local ipv4
  lineinfile: "dest=/etc/elasticsearch/elasticsearch.yml
               regexp='network.host:'
               line='network.host: _lo:ipv4_'"
  notify: restart elasticsearch
