---
- hosts: central-logging
  user: "{{ user }}"
  sudo: yes

  vars_files:
    - ../vars/global_vars.yml

  tasks:
    - include: ../tasks/elasticsearch-setup.yml

  handlers:
    - include: ../handlers/elasticsearch.yml
